Merging Changes from GSOC23 into main
honeynet/riotpot pull request #33
Opened 2023-08-14 15:23 UTC by eltsai

2023-08-19 07:17 UTC, RicYaben requested changes
In summary, we expect the following changes for this pull request:

* Place the services in the honeypot network
* Use Docker secrets or separated files as a way to add service credentials

Other than that, it looks good to me :) the rest of the thinks can be changed in future revisions

2023-08-19 07:17 UTC, RicYaben commented on build/docker/service/custom_ftpd/Dockerfile
> +ENV USERS="ftpuser|password"
It is a bit weird to have credentials directly in a Dockerfile. Perhaps load them from a file to docker-compose "secrets" tag and read from there.
Link: https://docs.docker.com/compose/use-secrets/

2023-08-19 07:17 UTC, RicYaben commented on build/docker/docker-compose.yaml
> +      default:
the default networks expose the services to the Internet. This is not the behavior we are looking for with Riotpot. These services must be hidden in a virtual local network!

choose the honeypot network instead

2023-08-19 07:17 UTC, RicYaben commented on build/docker/docker-compose.yaml
> +
missing network

2023-08-19 07:17 UTC, RicYaben commented on build/docker/docker-compose.yaml
> +      default:
same as above

2023-08-19 07:17 UTC, RicYaben commented on build/docker/docker-compose.yaml
> +      default:
private network please

2023-08-19 07:17 UTC, RicYaben commented on build/docker/docker-compose.yaml
> +      - USERS=ftpuser|password     # Set the default FTP user (you can add more users here)
see explanation to docker compose secrets
https://docs.docker.com/compose/use-secrets/

2023-08-19 07:17 UTC, RicYaben commented on build/docker/service/custom_httpd/Dockerfile
> +    && echo "</VirtualHost>" >> /usr/local/apache2/conf/httpd.conf
maybe it makes more sense to append a whole document to `/usr/local/apache2/conf/httpd.conf`?

2023-08-19 07:17 UTC, RicYaben commented on build/docker/service/custom_sshd/Dockerfile
> +#RUN echo "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPp/jbeIDrxDXW18vBuUxOj+N5msJe/elIJlgI4znfi4 riotpot@riotpot.com" >> /root/.ssh/authorized_keys
do these comments need to stay?

2023-08-19 07:17 UTC, RicYaben commented on build/docker/service/custom_sshd/Dockerfile
> +RUN echo 'root:password' | chpasswd
same as before with the secrets. Also, I am not sure this is the behavior we need. This allows to only one set of credentials to login to the service

2023-08-19 07:17 UTC, RicYaben commented on build/docker/service/custom_telnet/Dockerfile
> +CMD ["telnet", "localhost"]
Is this pinging localhost? I am not sure about it

2023-08-21 20:37 UTC, eltsai commented on build/docker/service/custom_ftpd/Dockerfile
> +ENV USERS="ftpuser|password"
(I am replying emojis to each threads as a reminder on each task has been completed)

2023-08-22 02:40 UTC, eltsai commented on build/docker/service/custom_telnet/Dockerfile
> +CMD ["telnet", "localhost"]
Oops I got this one wrong. The reason I got a response from port 23 is that I had a telnet server running on my local machine on port 23 (when testing I put the service on 2323). Rewriting this

2023-08-22 03:53 UTC, eltsai commented
HTTPS:
1. ✔️Placed in the honeypot network

SSH:
1. ✔️Placed in the honeypot network
2. ✔️Used docker secret for password based authentication
3. ✔️Add instructions in README for generating `ssh_users.txt` file.

Telnet:
1. ✔️Placed in the honeypot network
2. ✔️Rewrote dockerfile

FTP: 
1. ✖️Moved username and password config into `ftp_users.txt` --- the user name and passwords are set using  `USERS` variable. I tried reading it from file:

   ```
   # RUN export USERS=$(cat /tmp/ftp_users)
   # Set the USERS environment variable using an environment file
   RUN echo "USERS=$(cat /run/secrets/ftp_users)" >> /envfile
   ```

   But did not work out. Tried the sugguestion under this [[post](https://stackoverflow.com/questions/34911622/dockerfile-set-env-to-result-of-command?rq=3)](https://stackoverflow.com/questions/34911622/dockerfile-set-env-to-result-of-command?rq=3 ) but none of them works
2. ✔️Added a README on password and username configuration.
3. ✔️Placed in the honeypot network

2023-08-28 06:51 UTC, RicYaben approved these changes
Looks good :)

2023-08-28 06:51 UTC, merged